# evolution
# Autogenerated from man page /usr/share/man/man1/evolution.1.gz
complete -c evolution -s c -l component -d 'Start Evolution showing the specified component'
complete -c evolution -s g -l geometry -d 'Apply the given geometry to the main window'
complete -c evolution -l offline -d 'Start in offline mode'
complete -c evolution -l online -d 'Start in online mode'
complete -c evolution -l force-online -d 'Ignore network availability'
complete -c evolution -l force-shutdown -d 'Forcibly shut down Evolution and background Evolution-Data-Server processes'
complete -c evolution -l disable-eplugin -d 'Disable loading of any plugins'
complete -c evolution -l disable-preview -d 'Disable preview pane of Mail, Contacts and Tasks'
complete -c evolution -s i -l import -d 'Import URIs or filenames given as rest of arguments'

