# focuswriter
# Autogenerated from man page /usr/share/man/man1/focuswriter.1.gz
complete -c focuswriter -s h -l help -d 'Displays help on commandline options'
complete -c focuswriter -l help-all -d 'Displays help including Qt specific options'
complete -c focuswriter -s v -l version -d 'Displays version information'

