# gda-sql
# Autogenerated from man page /usr/share/man/man1/gda-sql.1.gz
complete -c gda-sql -l help -d 'Show command-line options'
complete -c gda-sql -s o -l output-file -d 'Specifies a file to which outputs are redirected'
complete -c gda-sql -s C -l command -d 'Run only single command (SQL or internal) and exit'
complete -c gda-sql -s f -l commands-file -d 'Execute commands from <filename>, then exit (except if -i specified)'
complete -c gda-sql -s i -l interactive -d 'Keep the console opened after executing a file (used with the -f option)'
complete -c gda-sql -s l -l list-dsn -d 'List configured data sources and exit'
complete -c gda-sql -s L -l list-providers -d 'List installed database providers and exit'
complete -c gda-sql -s s -l http-port -d 'Starts the embedded HTTP server on port <port>'
complete -c gda-sql -s t -l http-token -d 'Requires HTTP clients to authenticate by providing the <token phrase> (empty …'
complete -c gda-sql -l data-files-list -d 'Lists all the files used to hold information related to each connection (ie'
complete -c gda-sql -l data-files-purge -d 'Removes file used to hold information related to each connection for the crit…'

