# glabels-3
# Autogenerated from man page /usr/share/man/man1/glabels-3.1.gz
complete -c glabels-3 -s '?' -l help -d 'Display a summary of available command-line options'
complete -c glabels-3 -l usage -d 'Display a short usage summary'
complete -c glabels-3 -s v -l version -d 'Print program version information. PP  Options specific to glabels-batch'
complete -c glabels-3 -s o -l output -d 'Set output filename to filename.  (default="output. ps")'
complete -c glabels-3 -s s -l sheets -d 'Set number of sheets to n.  (default=1)'
complete -c glabels-3 -s c -l copies -d 'Set number of copies to n.  (default=1)'
complete -c glabels-3 -s f -l first -d 'Set label on first sheet to start printing from to n.  (default=1)'
complete -c glabels-3 -s l -l outline -d 'Print outlines around labels'
complete -c glabels-3 -s r -l reverse -d 'Print mirror image of labels'

