# iec16022
# Autogenerated from man page /usr/share/man/man1/iec16022.1.gz
complete -c iec16022 -s s -l size -d 'Sets the size of the generated barcode'
complete -c iec16022 -s c -l barcode -d 'Specifies the text to be encoded'
complete -c iec16022 -l ecc -d 'Sets the type of ecc to be used (default: 200)'
complete -c iec16022 -s i -l infile -d 'Read input data from file'
complete -c iec16022 -s o -l outfile -d 'Save output to file (instead of standard output)'
complete -c iec16022 -s f -l format -d 'Set the output type'
complete -c iec16022 -s '?' -l help -d 'Show summary of options'
complete -c iec16022 -l usage -d 'Show short overview of options'

