# lifeograph
# Autogenerated from man page /usr/share/man/man1/lifeograph.1.gz
complete -c lifeograph -l open -s o -d 'Sets the diary file to be opened'
complete -c lifeograph -l read-only -s r -d 'Run in read-only mode where no change is allowed'
complete -c lifeograph -l read-only-single -d 'Run for viewing a single file.  Logging out is not supported'
complete -c lifeograph -l ignore-locks -d 'Enables opening locked diary files'
complete -c lifeograph -l force-welcome -d 'Forces program to show the welcome screen'

