# lspst
# Autogenerated from man page /usr/share/man/man1/lspst.1.gz
complete -c lspst -s V -d 'Show program version and exit'
complete -c lspst -s d -d 'Specify name of debug log file'
complete -c lspst -s f -d 'Select the date format for long format listing.  Defaults to "%F %T"'
complete -c lspst -s l -d 'Use long format listing to show the Date, CC and BCC headers'
complete -c lspst -s h -d 'Show summary of options and exit'

