# ofxdump
# Autogenerated from man page /usr/share/man/man1/ofxdump.1.gz
complete -c ofxdump -s h -l help -d 'Print help and exit'
complete -c ofxdump -s V -l version -d 'Print version and exit'
complete -c ofxdump -s f -l import-format -d 'Force the file format of the file(s) specified (default=`AUTODETECT\')'
complete -c ofxdump -l list-import-formats -d 'List available import file formats \'import-format\' command'
complete -c ofxdump -l msg_parser -d 'Output file parsing messages  (default=off)'
complete -c ofxdump -l msg_debug -d 'Output messages meant for debugging (default=off)'
complete -c ofxdump -l msg_warning -d 'Output warning messages about abnormal conditions and unknown constructs  (de…'
complete -c ofxdump -l msg_error -d 'Output error messages  (default=on)'
complete -c ofxdump -l msg_info -d 'Output informational messages about the progress of the library  (default=on)'
complete -c ofxdump -l msg_status -d 'Output status messages  (default=on)'

