# povray
# Autogenerated from man page /usr/share/man/man1/povray.1.gz
complete -c povray -o display -d 'Display preview on display_name rather than the default display'
complete -c povray -o geometry -d 'Render the image with WIDTH and HEIGHT as the dimensions, and locate the wind…'
complete -c povray -o help -d 'Display the X Window System-specific options'
complete -c povray -o icon -d 'Start the preview window as an icon'
complete -c povray -o title -d 'Override the default preview window title with window_title'
complete -c povray -o visual -d 'Use the deepest visual of visual_type, if available, instead of the automatic…'

