# scribus
# Autogenerated from man page /usr/share/man/man1/scribus.1.gz
complete -c scribus -s l -l lang -d 'Overrides the system locale and runs Scribus in language xx'
complete -c scribus -o la -l langs-available -d 'Print a list of languages for which user interface translations are available'
complete -c scribus -s v -l version -d 'Prints the Scribus version number and exits'
complete -c scribus -s f -l file -d 'Open the specified file'
complete -c scribus -s h -l help -d 'Print a brief usage summary'
complete -c scribus -o fi -l font-info -d 'Shows the font file listing as Scribus starts'
complete -c scribus -o pi -l profile-info -d 'Shows the color profiles listing which Scribus can use'
complete -c scribus -o pr -l prefs -d 'Use filename as path for user given preferences'
complete -c scribus -o py -l python-script -d 'Run script in Python [with optional arguments]'
complete -c scribus -o ns -l no-splash -d 'Suppresses display of the splash screen during Scribus start-up'
complete -c scribus -o nns -l never-splash -d 'Stop the showing of the splashscreen on startup'
complete -c scribus -o sb -l swap-buttons -d 'Use right to left dialog button ordering (eg'
complete -c scribus -s u -l upgradecheck -d 'Downloads a file from our scribus server indicating latest available versions'

