# tenacity
# Autogenerated from man page /usr/share/man/man1/tenacity.1.gz
complete -c tenacity -l help -d 'Display a brief list of command line options'
complete -c tenacity -l version -d 'Display the Tenacity version number'
complete -c tenacity -l test -d 'run self diagnostics tests (only present in development builds)'
complete -c tenacity -l blocksize -d 'Set the Tenacity block size for writing files to disk to nnn bytes'

