# unrar-free
# Autogenerated from man page /usr/share/man/man1/unrar-free.1.gz
complete -c unrar-free -s x -l extract -d 'Extract files from archive (default)'
complete -c unrar-free -s t -l list -d 'List files in archive'
complete -c unrar-free -s f -l force -d 'Overwrite files when extracting'
complete -c unrar-free -l extract-newer -d 'Only extract newer files from the archive'
complete -c unrar-free -l extract-no-paths -d 'Don\'t create directories while extracting'
complete -c unrar-free -s p -l password -d 'Decrypt archive using a password'
complete -c unrar-free -s '?' -l help -d 'Show program help'
complete -c unrar-free -l usage -d 'Show short program usage message'
complete -c unrar-free -s V -l version -d 'Show version of program.  NON-FREE UNRAR COMPATIBLE SYNOPSIS'
complete -c unrar-free -o ep -d 'Don\'t create directories while extracting'
complete -c unrar-free -o o+ -d 'Overwrite files when extracting'
complete -c unrar-free -o o- -d 'Don\'t overwrite files when extracting'
complete -c unrar-free -o pPassword -d 'Decrypt archive using the password Password'
complete -c unrar-free -s u -d 'Only extract newer files from the archive'
complete -c unrar-free -s y -d 'Assume Yes on all queries.  Ineffective'

