# YACReaderLibrary
# Autogenerated from man page /usr/share/man/man1/YACReaderLibrary.1.gz
complete -c YACReaderLibrary -s h -d 'Display help text and exit'
complete -c YACReaderLibrary -s v -d 'Display version information and exit.  FEATURES'

