# YACReader
# Autogenerated from man page /usr/share/man/man1/YACReader.1.gz
complete -c YACReader -s h -d 'Display this text and exit'
complete -c YACReader -s v -d 'Display version information and exit.   FEATURES'

